<#
AstroQuant_MT5_AutoConnect_Setup.ps1
=====================================
STANDALONE installer — run this from ANY directory on your Windows machine.
No repo clone needed.

STEP 1: pip install MetaTrader5 requests
STEP 2: powershell -ExecutionPolicy Bypass -File AstroQuant_MT5_AutoConnect_Setup.ps1

OPTIONAL: Pass -BackendUrl to override the tunnel URL if it has changed.
Example:  .\AstroQuant_MT5_AutoConnect_Setup.ps1 -BackendUrl "https://your-new-tunnel.trycloudflare.com"
#>

param(
    [string]$BackendUrl    = "https://pat-med-integrated-ellis.trycloudflare.com",
    [string]$UploadToken   = "",
    [string]$PythonCommand = "py -3",
    [int]$IntervalSec      = 60,
    [string]$TaskName      = "AstroQuant-MT5-HTTP"
)

$ErrorActionPreference = "Stop"

# ── Install directory ─────────────────────────────────────────────────────────
$installDir = "$env:ProgramData\AstroQuant"
$logDir     = "$installDir\logs"
$scriptFile = "$installDir\mt5_auto_export.py"
$launcherBat = "$installDir\run_mt5_upload.bat"

if (-not (Test-Path $installDir)) { New-Item -ItemType Directory -Path $installDir | Out-Null }
if (-not (Test-Path $logDir))     { New-Item -ItemType Directory -Path $logDir     | Out-Null }

Write-Host ""
Write-Host "AstroQuant MT5 Auto-Connect Setup"
Write-Host "=================================="
Write-Host "Install dir : $installDir"
Write-Host "Backend URL : $BackendUrl"
Write-Host "Interval    : ${IntervalSec}s"
Write-Host ""

# ── Write Python uploader ─────────────────────────────────────────────────────
$pythonScript = @'
"""
AstroQuant MT5 Auto-Export
Auto-generated by AstroQuant_MT5_AutoConnect_Setup.ps1
Pulls XAUUSD M5 candles from MetaTrader5 and POSTs them to the AstroQuant
backend every AQ_INTERVAL_SECONDS (default 60).
"""
import logging, os, sys, time
from datetime import datetime, timezone

try:
    import MetaTrader5 as mt5
except ImportError:
    sys.exit("ERROR: MetaTrader5 not installed. Run: pip install MetaTrader5 requests")
try:
    import requests
except ImportError:
    sys.exit("ERROR: requests not installed. Run: pip install MetaTrader5 requests")

# ── Config from env vars (set by launcher batch) ──────────────────────────────
BACKEND_URL    = os.getenv("AQ_BACKEND_URL", "https://pat-med-integrated-ellis.trycloudflare.com").rstrip("/")
UPLOAD_TOKEN   = os.getenv("MCL_MT5_UPLOAD_TOKEN", "").strip()
INTERVAL       = int(os.getenv("AQ_INTERVAL_SECONDS", "60"))
SYMBOL         = os.getenv("AQ_SYMBOL", "XAUUSD")
TIMEFRAME      = mt5.TIMEFRAME_M5
BARS           = 500
ENDPOINT       = f"/market_causality/mt5_upload?symbol={SYMBOL}&timeframe=5m"

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
    handlers=[
        logging.StreamHandler(sys.stdout),
        logging.FileHandler(
            os.path.join(os.getenv("AQ_LOG_DIR", os.path.dirname(os.path.abspath(__file__))), "mt5_uploader.log"),
            encoding="utf-8",
        ),
    ],
)
log = logging.getLogger("aq_mt5")


def _to_csv(rates) -> str:
    lines = ["Date;Open;High;Low;Close;TickVolume;Volume;Spread"]
    for r in rates:
        dt = datetime.fromtimestamp(r[0], tz=timezone.utc).strftime("%Y.%m.%d %H:%M:%S")
        lines.append(f"{dt};{r[1]:.5f};{r[2]:.5f};{r[3]:.5f};{r[4]:.5f};{int(r[5])};{int(r[7])};{int(r[6])}")
    return "\n".join(lines)


def _push(csv: str) -> bool:
    url = BACKEND_URL + ENDPOINT
    hdrs = {"Content-Type": "text/csv"}
    if UPLOAD_TOKEN:
        hdrs["x-mt5-upload-token"] = UPLOAD_TOKEN
    try:
        r = requests.post(url, data=csv.encode(), headers=hdrs, timeout=15)
        if r.status_code == 200:
            j = r.json()
            log.info("OK  rows=%-4s  latest=%s  bytes=%s",
                     j.get("rows","?"), j.get("latest_date","?"), j.get("bytes","?"))
            return True
        log.warning("HTTP %s: %s", r.status_code, r.text[:160])
    except Exception as e:
        log.error("Upload error: %s", e)
    return False


def run():
    log.info("Starting  backend=%s  interval=%ds  symbol=%s", BACKEND_URL, INTERVAL, SYMBOL)
    if not mt5.initialize():
        log.error("MT5 initialize() failed: %s", mt5.last_error())
        sys.exit(1)
    log.info("MT5 connected. Export loop running...")
    last_epoch = None
    try:
        while True:
            rates = mt5.copy_rates_from_pos(SYMBOL, TIMEFRAME, 0, BARS)
            if rates is None or len(rates) == 0:
                log.warning("No rates from MT5: %s", mt5.last_error())
            else:
                epoch = int(rates[-1][0])
                ts = datetime.fromtimestamp(epoch, tz=timezone.utc)
                log.info("Pulled %d bars, latest=%s UTC", len(rates), ts)
                if epoch != last_epoch:
                    if _push(_to_csv(rates)):
                        last_epoch = epoch
                else:
                    log.info("No new candle yet — skipping upload")
            time.sleep(INTERVAL)
    except KeyboardInterrupt:
        log.info("Stopped.")
    finally:
        mt5.shutdown()
        log.info("MT5 disconnected.")


if __name__ == "__main__":
    run()
'@

Set-Content -Path $scriptFile -Value $pythonScript -Encoding UTF8
Write-Host "[1/3] Python uploader written to: $scriptFile"

# ── Write launcher batch ──────────────────────────────────────────────────────
$batContent = @"
@echo off
REM AstroQuant MT5 Auto-Connect launcher (auto-generated)
set AQ_BACKEND_URL=$BackendUrl
set MCL_MT5_UPLOAD_TOKEN=$UploadToken
set AQ_INTERVAL_SECONDS=$IntervalSec
set AQ_LOG_DIR=$logDir

echo [%DATE% %TIME%] MT5 uploader starting >> "$logDir\mt5_uploader_run.log"
$PythonCommand "$scriptFile" >> "$logDir\mt5_uploader_run.log" 2>&1
echo [%DATE% %TIME%] MT5 uploader exited  >> "$logDir\mt5_uploader_run.log"
"@

Set-Content -Path $launcherBat -Value $batContent -Encoding ASCII
Write-Host "[2/3] Launcher written to: $launcherBat"

# ── Register Task Scheduler job ───────────────────────────────────────────────
schtasks /Query /TN $TaskName *> $null
if ($LASTEXITCODE -eq 0) {
    schtasks /Delete /TN $TaskName /F | Out-Null
    Write-Host "      (removed existing task)"
}

schtasks /Create /F `
    /TN  $TaskName `
    /SC  ONLOGON `
    /RL  HIGHEST `
    /TR  "cmd.exe /c `"$launcherBat`"" | Out-Null

if ($LASTEXITCODE -eq 0) {
    Write-Host "[3/3] Task Scheduler job registered: $TaskName"
} else {
    Write-Warning "Task Scheduler registration failed — try running PowerShell as Administrator"
}

Write-Host ""
Write-Host "============================================================"
Write-Host " SETUP COMPLETE"
Write-Host "============================================================"
Write-Host " Script  : $scriptFile"
Write-Host " Launcher: $launcherBat"
Write-Host " Task    : $TaskName  (runs on every Windows login)"
Write-Host " Logs    : $logDir\"
Write-Host ""
Write-Host " To START now (no reboot needed):"
Write-Host "   schtasks /Run /TN `"$TaskName`""
Write-Host ""
Write-Host " To check logs:"
Write-Host "   notepad `"$logDir\mt5_uploader.log`""
Write-Host ""
Write-Host " To UPDATE the backend URL when tunnel changes:"
Write-Host "   .\AstroQuant_MT5_AutoConnect_Setup.ps1 -BackendUrl `"https://new-url.trycloudflare.com`""
Write-Host ""
Write-Host " To STOP:"
Write-Host "   taskkill /F /IM python.exe"
Write-Host ""
Write-Host " To UNINSTALL:"
Write-Host "   schtasks /Delete /TN `"$TaskName`" /F"
Write-Host "============================================================"
