<#
install_mt5_http_upload_task.ps1
================================
Run ONCE on your Windows machine (where MetaTrader5 is installed).
Creates a Windows Task Scheduler job that auto-starts on login and pushes
XAUUSD M5 candles to the AstroQuant backend every 60 seconds via HTTP.

PREREQUISITES (run once in an admin PowerShell):
    pip install MetaTrader5 requests

USAGE:
    powershell -ExecutionPolicy Bypass -File install_mt5_http_upload_task.ps1

OPTIONAL PARAMETERS:
    -BackendUrl    "https://your-tunnel.trycloudflare.com"  (overrides auto-detect)
    -UploadToken   "your-secret-token"                      (if MCL_MT5_UPLOAD_TOKEN is set)
    -IntervalSec   60                                       (push cadence, default 60)
    -TaskName      "AstroQuant-MT5-HTTP"
    -PythonCommand "py -3"                                  (or full python path)
#>

param(
    [string]$TaskName      = "AstroQuant-MT5-HTTP",
    [string]$BackendUrl    = "",          # empty = read from tunnel_url.txt or static fallback
    [string]$UploadToken   = "",          # MCL_MT5_UPLOAD_TOKEN
    [string]$PythonCommand = "py -3",     # e.g. "python" or "C:\Python311\python.exe"
    [int]$IntervalSec      = 60
)

$ErrorActionPreference = "Stop"

# ── Resolve paths ─────────────────────────────────────────────────────────────
$toolsDir    = $PSScriptRoot                              # tools\windows
$repoRoot    = Split-Path (Split-Path $toolsDir -Parent) -Parent  # repo root
$uploaderPy  = Join-Path (Split-Path $toolsDir -Parent) "mt5_auto_export_to_codespace.py"

if (-not (Test-Path $uploaderPy)) {
    throw "Uploader script not found: $uploaderPy`nExpected at tools\mt5_auto_export_to_codespace.py"
}

# ── Resolve backend URL ────────────────────────────────────────────────────────
if (-not $BackendUrl) {
    $tunnelFile = Join-Path $repoRoot "data\tunnel_url.txt"
    if (Test-Path $tunnelFile) {
        $BackendUrl = (Get-Content $tunnelFile -Raw).Trim().TrimEnd("/")
        Write-Host "Auto-detected backend URL from tunnel_url.txt: $BackendUrl"
    }
}
if (-not $BackendUrl) {
    $BackendUrl = "https://pat-med-integrated-ellis.trycloudflare.com"
    Write-Host "Using static fallback URL: $BackendUrl"
}

# ── Create launcher batch file next to this script ────────────────────────────
$launcherBat = Join-Path $toolsDir "run_mt5_http_upload.bat"
$logDir      = "$env:ProgramData\AstroQuant\logs"

$batContent = @"
@echo off
REM Auto-generated by install_mt5_http_upload_task.ps1 — do not edit manually.
REM Re-run the installer to regenerate with updated settings.

set AQ_BACKEND_URL=$BackendUrl
set MCL_MT5_UPLOAD_TOKEN=$UploadToken
set AQ_INTERVAL_SECONDS=$IntervalSec

if not exist "$logDir" mkdir "$logDir" 2>nul

echo [%DATE% %TIME%] MT5 HTTP uploader starting... >> "$logDir\mt5_http_uploader.log"
$PythonCommand "$uploaderPy" >> "$logDir\mt5_http_uploader.log" 2>&1
echo [%DATE% %TIME%] MT5 HTTP uploader exited. >> "$logDir\mt5_http_uploader.log"
"@

Set-Content -Path $launcherBat -Value $batContent -Encoding ASCII
Write-Host "Launcher written: $launcherBat"

# ── Register (or update) the Task Scheduler job ──────────────────────────────
# Remove old task with same name if it exists
schtasks /Query /TN $TaskName *> $null
if ($LASTEXITCODE -eq 0) {
    schtasks /Delete /TN $TaskName /F | Out-Null
    Write-Host "Removed existing task: $TaskName"
}

# Create: run on login, highest privileges, repeat every $IntervalSec seconds
# Windows Task Scheduler has a minimum repeat interval of 1 minute (60s), which
# matches the uploader's own internal cadence — the script loops internally.
$taskAction = "cmd.exe"
$taskArgs   = "/c `"$launcherBat`""

schtasks /Create /F `
    /TN $TaskName `
    /SC ONLOGON `
    /RL HIGHEST `
    /TR "$taskAction $taskArgs" | Out-Null

Write-Host ""
Write-Host "============================================================"
Write-Host " Task installed: $TaskName"
Write-Host " Launcher:       $launcherBat"
Write-Host " Backend URL:    $BackendUrl"
Write-Host " Log file:       $logDir\mt5_http_uploader.log"
Write-Host "============================================================"
Write-Host ""
Write-Host "To start NOW (without logging off):  schtasks /Run /TN `"$TaskName`""
Write-Host "To stop:                              taskkill /F /IM python.exe"
Write-Host "To uninstall:                         schtasks /Delete /TN `"$TaskName`" /F"
Write-Host ""
Write-Host "The task will auto-start on every Windows login from now on."
Write-Host "MT5 must be open and logged in for candle export to succeed."
