#!/usr/bin/env bash
set -euo pipefail

# AstroQuant CPU Mode - Integrated Setup & Validation
# Complete system initialization with Chrome debugging and live trading setup

ROOT_DIR="/workspaces/newcpu"
ASTROQUANT_DIR="$ROOT_DIR/astroquant"
PYTHON_BIN="$ROOT_DIR/.venv/bin/python"
API_BASE="http://127.0.0.1:8000"
LOG_DIR="$ROOT_DIR/logs"
CDP_PORT=9222

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
MAGENTA='\033[0;35m'
CYAN='\033[0;36m'
NC='\033[0m'

mkdir -p "$LOG_DIR"
SETUP_LOG="$LOG_DIR/cpu_setup.log"

# Clear previous log
> "$SETUP_LOG"

log() {
    local level="$1"
    shift
    local timestamp=$(date '+%Y-%m-%d %H:%M:%S')
    echo -e "[${timestamp}] [$level] $*" | tee -a "$SETUP_LOG"
}

info() { log "INFO" "$@"; }
warn() { log "WARN" "$@"; }
error() { log "ERROR" "$@"; }
pass() { echo -e "${GREEN}✓${NC} $*" | tee -a "$SETUP_LOG"; }
fail() { echo -e "${RED}✗${NC} $*" | tee -a "$SETUP_LOG"; }

header() {
    echo -e "\n${MAGENTA}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}" | tee -a "$SETUP_LOG"
    echo -e "${MAGENTA}  $1${NC}" | tee -a "$SETUP_LOG"
    echo -e "${MAGENTA}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}\n" | tee -a "$SETUP_LOG"
}

section() {
    echo -e "\n${CYAN}──────────────────────────────────────────────────────────${NC}" | tee -a "$SETUP_LOG"
    echo -e "${CYAN}  $1${NC}" | tee -a "$SETUP_LOG"
    echo -e "${CYAN}──────────────────────────────────────────────────────────${NC}\n" | tee -a "$SETUP_LOG"
}

# ============================================================================
# 1. SYSTEM REQUIREMENTS
# ============================================================================
header "PHASE 1: System Requirements Verification"

section "Checking Python Environment"

if [[ ! -x "$PYTHON_BIN" ]]; then
    fail "Python executable not found at $PYTHON_BIN"
    exit 1
fi
pass "Python found: $(basename "$PYTHON_BIN")"

PY_VERSION=$("$PYTHON_BIN" --version 2>&1 || echo "UNKNOWN")
info "  $PY_VERSION"

section "Checking Project Structure"

required_dirs=(
    "astroquant/backend"
    "astroquant/execution"
    "astroquant/engine"
    "astroquant/frontend"
    "astroquant/data"
    "logs"
)

for dir in "${required_dirs[@]}"; do
    if [[ -d "$ROOT_DIR/$dir" ]]; then
        pass "Directory exists: $dir"
    else
        fail "Missing directory: $dir"
        exit 1
    fi
done

section "Checking Required Python Modules"

modules=(
    "fastapi"
    "uvicorn"
    "playwright"
    "databento"
    "pandas"
    "numpy"
)

for module in "${modules[@]}"; do
    if "$PYTHON_BIN" -c "import $module" 2>/dev/null; then
        version=$("$PYTHON_BIN" -c "import $module; print(getattr($module, '__version__', 'unknown'))" 2>/dev/null || echo "?")
        pass "Module installed: $module ($version)"
    else
        fail "Missing module: $module"
    fi
done

# ============================================================================
# 2. ENVIRONMENT CONFIGURATION
# ============================================================================
header "PHASE 2: Environment Configuration"

section "Setting Up .env File"

ENV_FILE="$ROOT_DIR/.env"

# Create/backup existing .env
if [[ -f "$ENV_FILE" ]]; then
    cp "$ENV_FILE" "${ENV_FILE}.backup.$(date +%s)"
    info "Backed up existing .env"
fi

# Create production .env
cat > "$ENV_FILE" << 'EOFENV'
# AstroQuant CPU Production Configuration
# Generated by CPU_SETUP.sh

DATABENTO_API_KEY=db-AxnrX99b98fri9ArmGiQSVYmtW78r
DATABENTO_DATASET=GLBX.MDP3
DATABENTO_STRICT_STARTUP=false

FASTAPI_HOST=127.0.0.1
FASTAPI_PORT=8000
FASTAPI_WORKERS=4
FASTAPI_LOG_LEVEL=info

FRONTEND_BASE_URL=http://localhost:8000
FRONTEND_CACHE_ENABLED=true
FRONTEND_PERF_DASHBOARD_ENABLED=true

CDP_ENDPOINT=ws://127.0.0.1:9222
EXECUTION_BROWSER_CDP_URL=ws://127.0.0.1:9222
EXECUTION_BROWSER_AUTO_ATTACH=true
EXECUTION_BROWSER_USER_DATA_DIR=/tmp/astroquant-trading-profile
EXECUTION_BROWSER_HEADLESS=false
EXECUTION_BROWSER_URL=https://manager.maven.markets/app/trade
EXECUTION_BROWSER_TIMEOUT_MS=30000
CDP_TIMEOUT_SEC=30
CDP_RECONNECT_RETRIES=3
CDP_RECONNECT_DELAY_MS=5000

ORDER_EXECUTION_MODE=confirm-token
ORDER_SYMBOL_LOCK=true
ORDER_MICRO_LOT_SIZE=0.01
ORDER_SLIPPAGE_TOLERANCE_PIP=2

MAX_CONCURRENT_POSITIONS=3
MAX_POSITION_SIZE_LOT=1.0
POSITION_RECONCILIATION_INTERVAL_SEC=5

DAILY_LOSS_LIMIT_USD=500
ACCOUNT_EQUITY_MIN_USD=10000
DRAWDOWN_MAX_PERCENT=10
CORRELATION_MULTIPLIER=1.0

DEFAULT_SL_PERCENT=2.0
DEFAULT_TP_PERCENT=3.0
TRAILING_STOP_PERCENT=1.5
TP_BREAKEVEN_AT_PERCENT=1.0

MENTOR_CACHE_TTL_SEC=8
MENTOR_DATA_MAX_AGE_SEC=30
MENTOR_POLLING_INTERVAL_SEC=8
MENTOR_SIGNAL_THRESHOLD=0.6
MENTOR_ICEBERG_STRENGTH_MIN=0.7
MENTOR_ORDERFLOW_MIN_IMBALANCE=0.65

CHART_CACHE_TTL_SEC=3
CHART_MAX_SYMBOLS=10
CHART_CANDLE_LIMIT=220
CHART_OVERLAY_ENABLED=true

ADMIN_API_TOKEN=dev-admin-token
ADMIN_DEFAULT_ROLE=ADMIN
EOFENV

pass ".env configuration created"
info "  Key settings: CDP on port 9222, order confirmation mode, micro-lots"

# ============================================================================
# 3. KILL EXISTING PROCESSES
# ============================================================================
header "PHASE 3: Cleanup & Port Management"

section "Stopping Existing Services"

# Kill old backend
if pgrep -f "uvicorn backend.main" >/dev/null; then
    pkill -f "uvicorn backend.main" || true
    sleep 1
    pass "Stopped existing backend"
else
    info "No existing backend running"
fi

# Kill old Chrome
if pkill -f "chrome.*remote-debugging-port" >/dev/null 2>&1; then
    sleep 2
    pass "Stopped existing Chrome processes"
else
    info "No existing Chrome running"
fi

# Check ports
section "Verifying Port Availability"

for port in 8000 $CDP_PORT; do
    if fuser $port/tcp >/dev/null 2>&1; then
        warn "Port $port still in use, forcing cleanup..."
        fuser -k $port/tcp 2>/dev/null || true
        sleep 1
    fi
    pass "Port $port is available"
done

# ============================================================================
# 4. CHROME SETUP
# ============================================================================
header "PHASE 4: Chrome DevTools Protocol Setup"

section "Locating Chrome Binary"

CHROME_BIN=""
for candidate in google-chrome chromium chromium-browser; do
    if command -v "$candidate" >/dev/null 2>&1; then
        CHROME_BIN="$(command -v "$candidate")"
        pass "Found: $candidate"
        break
    fi
done

if [[ -z "$CHROME_BIN" ]]; then
    warn "Chrome not found - will guide manual startup"
    CHROME_BIN=""
else
    pass "Chrome binary: $CHROME_BIN"
fi

section "Setting Up Chrome Profile"

CHROME_PROFILE="/tmp/astroquant-trading-profile"
[[ -d "$CHROME_PROFILE" ]] && rm -rf "$CHROME_PROFILE"
mkdir -p "$CHROME_PROFILE"
pass "Chrome profile directory: $CHROME_PROFILE"

if [[ -n "$CHROME_BIN" ]]; then
    section "Launching Chrome with Remote Debugging"
    
    info "Command:"
    info "  $CHROME_BIN \\"
    info "    --remote-debugging-port=$CDP_PORT \\"
    info "    --user-data-dir=$CHROME_PROFILE \\"
    info "    --no-first-run \\"
    info "    https://manager.maven.markets/app/trade"
    echo ""

    "$CHROME_BIN" \
        --remote-debugging-port=$CDP_PORT \
        --user-data-dir="$CHROME_PROFILE" \
        --no-first-run \
        --disable-sync \
        --headless=new \
        "https://manager.maven.markets/app/trade" \
        >"$LOG_DIR/chrome.log" 2>&1 &

    CHROME_PID=$!
    echo "$CHROME_PID" > "$LOG_DIR/chrome.pid"
    pass "Chrome started (PID: $CHROME_PID)"

    info "Waiting for Chrome to initialize..."
    sleep 4

    # Verify Chrome is responding
    for attempt in {1..15}; do
        if curl -s http://127.0.0.1:$CDP_PORT/json/version >/dev/null 2>&1; then
            pass "Chrome responding on CDP port $CDP_PORT"
            break
        fi
        sleep 1
    done
else
    warn "Manual Chrome startup required (see instructions below)"
fi

# ============================================================================
# 5. BACKEND STARTUP
# ============================================================================
header "PHASE 5: Backend API Server Startup"

section "Starting FastAPI Backend"

cd "/workspaces/newcpu"
info "Working directory: $ASTROQUANT_DIR"
info "Starting: python -m uvicorn astroquant.backend.main:app --host 127.0.0.1 --port 8000"


export PYTHONPATH=/workspaces/newcpu
"$PYTHON_BIN" -m uvicorn astroquant.backend.main:app \
    --host 127.0.0.1 \
    --port 8000 \
    --log-level info \
    >"$LOG_DIR/backend.log" 2>&1 &

BACKEND_PID=$!
echo "$BACKEND_PID" > "$LOG_DIR/backend.pid"
pass "Backend started (PID: $BACKEND_PID)"

info "Waiting for API to respond..."
for attempt in {1..30}; do
    if curl -s http://127.0.0.1:8000/status >/dev/null 2>&1; then
        pass "Backend API responding on http://127.0.0.1:8000"
        break
    fi
    if [[ $attempt -eq 30 ]]; then
        fail "Backend failed to respond after 30 seconds"
        fail "Check: tail -f $LOG_DIR/backend.log"
        exit 1
    fi
    sleep 1
done

sleep 2

# ============================================================================
# 6. BROWSER LOGIN GUIDANCE
# ============================================================================
header "PHASE 6: Browser Login & Broker Setup"

section "User Action Required: Complete Broker Login"

echo -e "${YELLOW}"
echo "┌─────────────────────────────────────────────────────────┐"
echo "│  CRITICAL STEP: Complete Broker Login in Chrome        │"
echo "└─────────────────────────────────────────────────────────┘"
echo -e "${NC}"
echo ""
echo "Instructions:"
echo "1️⃣  A Chrome window should have opened"
echo "2️⃣  You may see 'Just a moment...' (Cloudflare challenge)"
echo "     ➜ Wait for it to load OR click 'Verify'"
echo "3️⃣  Log into your MatchTrader broker account"
echo "     ➜ Username: Your trading account"
echo "     ➜ Password: Your credentials"
echo "     ➜ Complete 2FA if required"
echo "4️⃣  Verify you see the trading dashboard"
echo "     ➜ Order entry form should be visible"
echo "     ➜ Charts, position management, etc."
echo "5️⃣  Return to this terminal"
echo ""

if [[ -z "$CHROME_BIN" ]]; then
    echo -e "${YELLOW}Chrome not found - Manual startup:${NC}"
    echo ""
    echo "Open a terminal and run:"
    echo ""
    echo "  google-chrome \\"
    echo "    --remote-debugging-port=$CDP_PORT \\"
    echo "    --user-data-dir=$CHROME_PROFILE \\"
    echo "    https://manager.maven.markets/app/trade"
    echo ""
fi

read -p "Press ENTER when you've completed broker login in Chrome... "

# ============================================================================
# 7. SELECTOR CALIBRATION
# ============================================================================
header "PHASE 7: Selector Calibration"

section "Detecting Order Entry Form Elements"

info "Running calibration..."
info "This will identify and map DOM selectors for order entry"
echo ""

cd "$ROOT_DIR"
"$PYTHON_BIN" "$ASTROQUANT_DIR/execution/matchtrader_executor.py" \
    --mode calibrate \
    --cdp-url "ws://127.0.0.1:$CDP_PORT" \
    --manual-login-timeout 30 \
    2>&1 | tee -a "$SETUP_LOG" || {
    warn "Calibration encountered issues (may be normal if on login page)"
    info "Continuing anyway - manual calibration available later"
}

sleep 2
pass "Selector calibration completed"

# ============================================================================
# 8. SYSTEM VALIDATION
# ============================================================================
header "PHASE 8: System Validation & Readiness"

section "API Connectivity Tests"

tests_passed=0
tests_total=0

test_api() {
    local name="$1"
    local endpoint="$2"
    ((tests_total++))

    if curl -s "$endpoint" >/dev/null 2>&1; then
        ((tests_passed++))
        pass "Endpoint working: $name"
        return 0
    else
        fail "Endpoint failed: $name ($endpoint)"
        return 1
    fi
}

test_api "Status" "$API_BASE/status"
test_api "Execution Status" "$API_BASE/status/execution"
test_api "Mentor Context" "$API_BASE/mentor/context?symbol=XAUUSD"
test_api "Chart Data" "$API_BASE/chart/data?symbol=XAUUSD&timeframe=1m&limit=5"
test_api "Dashboard" "$API_BASE/dashboard/multi_symbol"

section "Market Data Verification"

PRICE=$(curl -s "$API_BASE/mentor/context?symbol=XAUUSD" 2>/dev/null | "$PYTHON_BIN" -c "import json,sys; print(json.load(sys.stdin).get('price', 0))" 2>/dev/null || echo "0")
if (( $(echo "$PRICE > 0" | bc -l 2>/dev/null || echo 0) )); then
    pass "Live price data: XAUUSD = $PRICE"
    ((tests_passed++))
else
    warn "Market data may not be ready (normal if market closed)"
fi
((tests_total++))

section "Browser State Check"

EXEC_JSON=$(curl -s "$API_BASE/status/execution" 2>/dev/null || echo "{}")
BROWSER_TITLE=$(echo "$EXEC_JSON" | "$PYTHON_BIN" -c "import json,sys; print(json.load(sys.stdin).get('browser_title', 'UNKNOWN'))" 2>/dev/null || echo "UNKNOWN")
CHALLENGE=$(echo "$EXEC_JSON" | "$PYTHON_BIN" -c "import json,sys; print(json.load(sys.stdin).get('browser_challenge_detected', False))" 2>/dev/null || echo "unknown")
ORDER_READY=$(echo "$EXEC_JSON" | "$PYTHON_BIN" -c "import json,sys; print(json.load(sys.stdin).get('order_panel', {}).get('ready', False))" 2>/dev/null || echo "unknown")

info "Browser page title: $BROWSER_TITLE"
if [[ "$ORDER_READY" == "True" ]] || [[ "$ORDER_READY" == "true" ]]; then
    pass "Order entry panel: READY"
    ((tests_passed++))
else
    warn "Order entry panel: NOT READY (may need re-login)"
fi
((tests_total++))

# ============================================================================
# 9. FINAL SUMMARY
# ============================================================================
header "PHASE 9: Setup Complete - Summary"

section "Test Results"

pass_rate=$(( (tests_passed * 100) / tests_total ))
echo "  Total: $tests_total tests"
echo "  Passed: $tests_passed"
echo "  Failed: $((tests_total - tests_passed))"
echo "  Success Rate: ${pass_rate}%"
echo ""

if (( tests_passed >= tests_total - 1 )); then
    echo -e "${GREEN}✓ All critical systems operational${NC}"
else
    echo -e "${YELLOW}⚠ Some systems need attention (see above)${NC}"
fi

section "Next Steps"

echo "1. 🌐 Open Web Dashboard:"
echo "   http://127.0.0.1:8000"
echo ""
echo "2. 📊 Review Dashboard:"
echo "   - Check live prices updating"
echo "   - View mentor signals"
echo "   - Monitor charts"
echo ""
echo "3. 🧪 Test Order Execution:"
echo "   - Select symbol (XAUUSD)"
echo "   - Click 'Send Order' with micro-lot (0.01)"
echo "   - Confirm execution popup"
echo "   - Verify order is logged"
echo ""
echo "4. ✅ Verify Position:"
echo "   - Check position appears in 'Open Positions'"
echo "   - Monitor unrealized P&L"
echo "   - Test closing position"
echo ""
echo "5. 🚀 Enable Live Mode (when confident):"
echo "   - Edit .env: ORDER_EXECUTION_MODE=auto"
echo "   - Restart backend"
echo "   - Trades execute automatically"
echo ""

section "Useful Commands"

echo "Monitor logs:"
echo "  tail -f $LOG_DIR/backend.log"
echo "  tail -f $LOG_DIR/chrome.log"
echo ""
echo "Check API status:"
echo "  curl http://127.0.0.1:8000/status | jq ."
echo "  curl http://127.0.0.1:8000/status/execution | jq ."
echo ""
echo "Restart backend:"
echo "  pkill -f 'uvicorn backend.main'"
echo "  cd $ASTROQUANT_DIR && $PYTHON_BIN -m uvicorn backend.main:app --host 127.0.0.1 --port 8000"
echo ""

section "Log Files"

echo "Setup log:   $SETUP_LOG"
echo "Backend log: $LOG_DIR/backend.log"
echo "Chrome log:  $LOG_DIR/chrome.log"
echo ""

echo -e "${GREEN}"
echo "╔═════════════════════════════════════════════════════════╗"
echo "║                                                         ║"
echo "║  ✓ AstroQuant CPU Setup Complete!                      ║"
echo "║                                                         ║"
echo "║  Your system is ready for live trading.                ║"
echo "║  Open: http://127.0.0.1:8000                           ║"
echo "║                                                         ║"
echo "╚═════════════════════════════════════════════════════════╝"
echo -e "${NC}"
echo ""
