#!/usr/bin/env bash
set -euo pipefail

# AstroQuant Live Trading Launch Script
# Complete setup with Chrome DevTools Protocol (CDP) debugging and selector calibration

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKEND_DIR="$ROOT_DIR/astroquant"
VENV_BIN="$ROOT_DIR/.venv/bin"
PYTHON_BIN="$VENV_BIN/python"
CHROME_PROFILE="/tmp/astroquant-trading-profile"
CDP_PORT=9222
CDP_URL="ws://127.0.0.1:${CDP_PORT}"
BROKER_URL="https://manager.maven.markets/app/trade"
LOG_DIR="$ROOT_DIR/logs"
STRICT_PREFLIGHT_SCRIPT="$ROOT_DIR/preflight_strict.sh"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Ensure logs directory exists
mkdir -p "$LOG_DIR"
LOG_FILE="$LOG_DIR/live_launch.log"

log() {
    local level="$1"
    shift
    local msg="$*"
    local timestamp=$(date '+%Y-%m-%d %H:%M:%S')
    echo -e "[${timestamp}] [${level}] ${msg}" | tee -a "$LOG_FILE"
}

info() { log "INFO" "$@"; }
warn() { log "WARN" "$@"; }
error() { log "ERROR" "$@"; }
success() { log "✓" "$@"; }

header() {
    echo -e "\n${BLUE}╔════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${BLUE}║${NC} $1"
    echo -e "${BLUE}╚════════════════════════════════════════════════════════════╝${NC}\n"
}

# ============================================================================
# 1. Pre-flight checks
# ============================================================================
header "Pre-Flight Checks"

if [[ ! -x "$PYTHON_BIN" ]]; then
    error "Python not found at $PYTHON_BIN"
    exit 1
fi
success "Python environment found: $PYTHON_BIN"

if [[ ! -d "$BACKEND_DIR" ]]; then
    error "Backend directory not found: $BACKEND_DIR"
    exit 1
fi
success "Backend directory found: $BACKEND_DIR"

# Check if Chrome is available
CHROME_BIN=""
if command -v google-chrome >/dev/null 2>&1; then
    CHROME_BIN="$(command -v google-chrome)"
elif command -v chromium >/dev/null 2>&1; then
    CHROME_BIN="$(command -v chromium)"
elif command -v chromium-browser >/dev/null 2>&1; then
    CHROME_BIN="$(command -v chromium-browser)"
else
    warn "Chrome/Chromium not found. You'll need to start it manually with:"
    warn "  google-chrome --remote-debugging-port=$CDP_PORT --user-data-dir=$CHROME_PROFILE '$BROKER_URL'"
    CHROME_BIN=""
fi

if [[ -n "$CHROME_BIN" ]]; then
    success "Chrome found: $CHROME_BIN"
fi

# ============================================================================
# 2. Setup environment configuration
# ============================================================================
header "Setting Up Environment Configuration"

ENV_FILE="$ROOT_DIR/.env"
ENV_BACKUP="${ENV_FILE}.backup"

# Backup existing .env if it exists
if [[ -f "$ENV_FILE" ]]; then
    cp "$ENV_FILE" "$ENV_BACKUP"
    info "Backed up existing .env to $ENV_BACKUP"
fi

# Create/update .env with live trading configuration
cat > "$ENV_FILE" << 'EOFENV'
# AstroQuant Live Trading Configuration
# Generated by LIVE_LAUNCH.sh

# =============================================================================
# Backend Configuration
# =============================================================================
FASTAPI_HOST=127.0.0.1
FASTAPI_PORT=8000
FASTAPI_WORKERS=4
FASTAPI_LOG_LEVEL=info

# Frontend
FRONTEND_BASE_URL=http://localhost:8000
FRONTEND_CACHE_ENABLED=true
FRONTEND_PERF_DASHBOARD_ENABLED=true

# =============================================================================
# CRITICAL: Chrome DevTools Protocol (CDP) for Playwright/Execution
# =============================================================================

# CDP connection settings - MUST match Chrome's remote debugging port
CDP_ENDPOINT=ws://127.0.0.1:9222
EXECUTION_BROWSER_CDP_URL=ws://127.0.0.1:9222
CDP_TIMEOUT_SEC=30
CDP_RECONNECT_RETRIES=3
CDP_RECONNECT_DELAY_MS=5000

# Browser configuration
EXECUTION_BROWSER_USER_DATA_DIR=/tmp/astroquant-trading-profile
EXECUTION_BROWSER_AUTO_ATTACH=true
EXECUTION_BROWSER_HEADLESS=false
EXECUTION_BROWSER_URL=https://manager.maven.markets/app/trade
EXECUTION_BROWSER_TIMEOUT_MS=30000

# Broker credentials (if using auto-login)
# EXECUTION_LOGIN_USERNAME=your_username
# EXECUTION_LOGIN_PASSWORD=your_password

# =============================================================================
# Market Data Feed (Databento)
# =============================================================================
DATABENTO_API_KEY=db-AxnrX99b98fri9ArmGiQSVYmtW78r
DATABENTO_DATASET=GLBX.MDP3
DATABENTO_STRICT_STARTUP=false

# =============================================================================
# Order Entry & Risk Management
# =============================================================================

# Order execution mode
# dry-run: Log only, no real trades
# confirm-token: Wait for user confirmation before each trade
# auto: Auto-execute (use only after validation!)
ORDER_EXECUTION_MODE=confirm-token
ORDER_SYMBOL_LOCK=true
ORDER_MICRO_LOT_SIZE=0.01
ORDER_SLIPPAGE_TOLERANCE_PIP=2

# Position Management
MAX_CONCURRENT_POSITIONS=3
MAX_POSITION_SIZE_LOT=1.0
POSITION_RECONCILIATION_INTERVAL_SEC=5

# Risk Controls
DAILY_LOSS_LIMIT_USD=500
ACCOUNT_EQUITY_MIN_USD=10000
DRAWDOWN_MAX_PERCENT=10
CORRELATION_MULTIPLIER=1.0

# Stop Loss / Take Profit
DEFAULT_SL_PERCENT=2.0
DEFAULT_TP_PERCENT=3.0
TRAILING_STOP_PERCENT=1.5
TP_BREAKEVEN_AT_PERCENT=1.0

# =============================================================================
# Mentor Engine Configuration
# =============================================================================
MENTOR_CACHE_TTL_SEC=8
MENTOR_DATA_MAX_AGE_SEC=30
MENTOR_POLLING_INTERVAL_SEC=8
MENTOR_SIGNAL_THRESHOLD=0.6
MENTOR_ICEBERG_STRENGTH_MIN=0.7
MENTOR_ORDERFLOW_MIN_IMBALANCE=0.65

# =============================================================================
# Chart & Technical Analysis
# =============================================================================
CHART_CACHE_TTL_SEC=3
CHART_MAX_SYMBOLS=10
CHART_CANDLE_LIMIT=220
CHART_OVERLAY_ENABLED=true

# =============================================================================
# Admin Configuration
# =============================================================================
ADMIN_API_TOKEN=dev-admin-token
ADMIN_DEFAULT_ROLE=ADMIN
EOFENV

success "Environment configuration created at $ENV_FILE"

# ============================================================================
# 3. Kill any existing Chrome processes
# ============================================================================
header "Cleaning Up Open Ports"

# Check if Chrome is already running on the CDP port
if fuser $CDP_PORT/tcp >/dev/null 2>&1; then
    warn "Something is already using port $CDP_PORT"
    EXISTING_PID=$(fuser $CDP_PORT/tcp 2>/dev/null | awk '{print $1}' | head -1)
    if [[ -n "$EXISTING_PID" ]]; then
        info "Attempting to kill process $EXISTING_PID..."
        kill -9 "$EXISTING_PID" 2>/dev/null || true
        sleep 1
    fi
fi
success "Port $CDP_PORT is available"

# Kill any stray Chrome processes
pkill -f "chrome.*remote-debugging-port" || true
sleep 1
success "Cleaned up any stray Chrome processes"

# ============================================================================
# 4. Start Chrome with Remote Debugging
# ============================================================================
header "Launching Chrome with Remote Debugging"

if [[ -n "$CHROME_BIN" ]]; then
    # Clean up old profile
    [[ -d "$CHROME_PROFILE" ]] && rm -rf "$CHROME_PROFILE"
    mkdir -p "$CHROME_PROFILE"

    info "Starting Chrome..."
    info "  Binary: $CHROME_BIN"
    info "  Profile: $CHROME_PROFILE"
    info "  CDP Port: $CDP_PORT"
    info "  Target URL: $BROKER_URL"

    # Start Chrome in background with logging
    "$CHROME_BIN" \
        --remote-debugging-port=$CDP_PORT \
        --user-data-dir="$CHROME_PROFILE" \
        --no-first-run \
        --no-default-browser-check \
        --disable-sync \
        --disable-default-apps \
        --disable-extensions \
        --headless=new \
        "$BROKER_URL" \
        >"$LOG_DIR/chrome.log" 2>&1 &

    CHROME_PID=$!
    echo "$CHROME_PID" > "$LOG_DIR/chrome.pid"
    success "Chrome launched with PID: $CHROME_PID"
    info "Chrome logs: $LOG_DIR/chrome.log"

    # Wait for Chrome to start
    info "Waiting for Chrome to initialize..."
    sleep 3

    # Verify Chrome is responding on CDP port
    for attempt in {1..10}; do
        if curl -s http://127.0.0.1:$CDP_PORT/json/version >/dev/null 2>&1; then
            success "Chrome is responding on CDP port $CDP_PORT"
            break
        fi
        if [[ $attempt -eq 10 ]]; then
            warn "Chrome didn't respond on CDP port after 10 attempts"
            warn "You may need to manually access Chrome and complete the login"
        fi
        sleep 1
    done
else
    warn "Chrome not found. Starting manual instructions..."
    echo ""
    echo -e "${YELLOW}MANUAL CHROME STARTUP REQUIRED${NC}"
    echo "Open a terminal and run:"
    echo ""
    echo -e "${YELLOW}google-chrome \\${NC}"
    echo -e "${YELLOW}  --remote-debugging-port=$CDP_PORT \\${NC}"
    echo -e "${YELLOW}  --user-data-dir=$CHROME_PROFILE \\${NC}"
    echo -e "${YELLOW}  '$BROKER_URL'${NC}"
    echo ""
    echo "Then return to this terminal."
    read -p "Press ENTER when Chrome is open and you've logged in..."
fi

# ============================================================================
# 5. Start Backend API Server
# ============================================================================
header "Starting Backend API Server"

info "Starting FastAPI backend from: $BACKEND_DIR"

cd "/workspaces/newcpu"

# Start backend in background

export PYTHONPATH=/workspaces/newcpu
"$PYTHON_BIN" -m uvicorn astroquant.backend.main:app \
    --host 127.0.0.1 \
    --port 8000 \
    --log-level info \
    >"$LOG_DIR/backend.log" 2>&1 &

BACKEND_PID=$!
echo "$BACKEND_PID" > "$LOG_DIR/backend.pid"
success "Backend started with PID: $BACKEND_PID"
info "Backend logs: $LOG_DIR/backend.log"

# Wait for backend to be ready
info "Waiting for backend API to respond..."
for attempt in {1..20}; do
    if curl -s http://127.0.0.1:8000/status >/dev/null 2>&1; then
        success "Backend API is responding on http://127.0.0.1:8000"
        break
    fi
    if [[ $attempt -eq 20 ]]; then
        error "Backend API didn't respond after 20 attempts"
        error "Check logs at: $LOG_DIR/backend.log"
        exit 1
    fi
    sleep 1
done

sleep 2

# ============================================================================
# 6. Wait for Browser Login
# ============================================================================
header "Browser Login & DOM Setup"

echo -e "${YELLOW}Critical Step: Complete broker login in Chrome${NC}"
echo ""
echo "Instructions:"
echo "1. Focus the Chrome window that just opened"
echo "2. Complete any Cloudflare challenge ('Just a moment...')"
echo "3. Log into your MatchTrader broker account"
echo "4. Ensure you see the order entry form"
echo "5. Return to this terminal and press ENTER"
echo ""

read -p "Press ENTER when browser is ready and logged into the broker..."

# ============================================================================
# 7. Verify Browser Connection
# ============================================================================
header "Verifying Browser Connection"

info "Checking browser state..."
EXEC_STATUS=$(curl -s http://127.0.0.1:8000/status/execution | "$PYTHON_BIN" -c "import json, sys; data=json.load(sys.stdin); print(data.get('browser_title', 'UNKNOWN'))" 2>/dev/null || echo "UNKNOWN")

if [[ "$EXEC_STATUS" == *"Just a moment"* ]] || [[ "$EXEC_STATUS" == "UNKNOWN" ]]; then
    warn "Browser still showing challenge or DOM not loaded"
    warn "Browser title: $EXEC_STATUS"
    warn "Retrying..."
    sleep 3
fi

# ============================================================================
# 8. Strict Preflight Gate
# ============================================================================
header "Strict Preflight Gate"

if [[ ! -x "$STRICT_PREFLIGHT_SCRIPT" ]]; then
    chmod +x "$STRICT_PREFLIGHT_SCRIPT"
fi

info "Running strict preflight checks (feed key + CDP + execution live checks)..."
if ! bash "$STRICT_PREFLIGHT_SCRIPT" http://127.0.0.1:8000 2>&1 | tee -a "$LOG_FILE"; then
    error "Strict preflight failed. Blocking launch until issues are fixed."
    exit 1
fi
success "Strict preflight passed"

# ============================================================================
# 9. Calibrate Selectors
# ============================================================================
header "Calibrating Selectors"

info "Running selector calibration..."
info "This will detect order entry form elements..."

cd "$ROOT_DIR"
"$PYTHON_BIN" astroquant/execution/matchtrader_executor.py \
    --mode calibrate \
    --cdp-url "$CDP_URL" \
    --manual-login-timeout 30 \
    2>&1 | tee -a "$LOG_FILE"

success "Selector calibration completed"

# ============================================================================
# 10. Final System Check
# ============================================================================
header "Final System Readiness Check"

info "Running comprehensive health check..."
bash "$ROOT_DIR/health_check.sh" 2>&1 | tee -a "$LOG_FILE"

# ============================================================================
# 11. Summary & Next Steps
# ============================================================================
header "Live Trading Setup Complete!"

echo -e "${GREEN}✓ Chrome launched with remote debugging${NC}"
echo -e "${GREEN}✓ Backend API running on http://127.0.0.1:8000${NC}"
echo -e "${GREEN}✓ Selectors calibrated${NC}"
echo ""

echo -e "${BLUE}NEXT STEPS:${NC}"
echo ""
echo "1. Open the Web Dashboard:"
echo -e "   ${YELLOW}http://127.0.0.1:8000${NC}"
echo ""
echo "2. Verify trading signals (select symbol in dashboard):"
echo "   - Check mentor data updates"
echo "   - Verify price feeds are live"
echo "   - Review Gann, ICT, and Iceberg signals"
echo ""
echo "3. Test dry-run execution (no real trades):"
echo "   - In dashboard, click 'Send Order' with confirm-token mode"
echo "   - Verify order is logged in Chrome DevTools"
echo ""
echo "4. Verify position reconciliation:"
echo -e "   ${YELLOW}curl http://127.0.0.1:8000/admin/control/reconcile_positions${NC}"
echo ""
echo "5. When ready for LIVE trading:"
echo "   - Change ORDER_EXECUTION_MODE=auto in .env"
echo "   - Restart backend: source $LOG_DIR/restart_backend.sh"
echo "   - Enable real order execution in dashboard"
echo ""

echo -e "${BLUE}Logs Location:${NC}"
echo "  Chrome:  $LOG_DIR/chrome.log"
echo "  Backend: $LOG_DIR/backend.log"
echo "  Launch:  $LOG_FILE"
echo ""

echo -e "${BLUE}PIDs (for monitoring):${NC}"
echo "  Chrome:  $(cat $LOG_DIR/chrome.pid 2>/dev/null || echo 'unknown')"
echo "  Backend: $(cat $LOG_DIR/backend.pid 2>/dev/null || echo 'unknown')"
echo ""

# Create restart script
cat > "$LOG_DIR/restart_backend.sh" << 'EOFSCRIPT'
#!/bin/bash
cd /workspaces/newcpu/astroquant
pkill -f "uvicorn backend.main" || true
sleep 1
/workspaces/newcpu/.venv/bin/python -m uvicorn backend.main:app --host 127.0.0.1 --port 8000 --log-level info
EOFSCRIPT
chmod +x "$LOG_DIR/restart_backend.sh"

echo -e "${GREEN}🚀 System Ready for Live Trading!${NC}"
echo ""
